# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac0c17f1edb9ee8486374af327d9c315d6c44acb8e7fe090e765d2ae685fc92a458eedd73c43d1abea0b7f5a5a08273b855df3e5cbf245e7fd1e926028c0c7df

test:
  secret_key_base: 9be6bf67a2017817bb8d8e1f08e7a472810619d17474cb069fbfa67ade0dae03ed0967c156571b8a20e3e866fd32ac27faae5adc383511ec954d87170c97811c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
